drivers: soc: Sync timerqueue variable on event timer
Due last changes on timequeue from common kernel at fe6430deeb4f16921db89a7a19e0d10b6ce118bb & ef2e640,
it changes some variable that are used in event timer.c, that are:

.head = RB_ROOT,
.next = NULL,

Both of that variable was changed from:
.head -> rb_root
= RB_ROOT -> rb_root_cached
.next -> removed

So change that variable to sync code with latest change from common kernel to fix compilation issue.

../drivers/soc/qcom/event_timer.c:54:3: error: field designator 'head' does not refer to any field in type 'typeof(struct timerqueue_head)' (aka 'struct timerqueue_head')
        .head = RB_ROOT_CACHED,
         ^
../drivers/soc/qcom/event_timer.c:55:3: error: field designator 'next' does not refer to any field in type 'typeof(struct timerqueue_head)' (aka 'struct timerqueue_head')
        .next = NULL,
         ^
2 errors generated.

Signed-off-by: Nicklas373 <herlambangdicky5@gmail.com>
Signed-off-by: Risti699 <wahhap10@gmail.com>